### ISSUE TITLE
Location of index.php

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.core#3]
The current location of the index.php file is set to the public directory. However this means that PHP will be accessing files outside the configured website root directory.

This has probably been done so that you do not have other folders available to the outside world.

However this also means that Xentriq will need to be able to access files that have not been configured to be under the website root folder.

I could imagine that this might be an issue for some deployments, any ideas on this?

**Comment by ttveldhuis** [comment]
This was indeed done to prevent files and folders such as templates being directly available since the 'raw' content of these files should not be available to the 'public'.  

This does mean that there is content outside the public folder (config, private, data) that might need to be readable by Xentriq. Currently this is not configurable and the names of those folders are fixed. 

Do you have have any suggestions on how to approach this for installations where this might be a problem?

**Comment by mpwaldhorst** [comment]
Maybe in that case it would be possible to add htaccess files in those directories. Although probably this will not work in webservers other than apache. Probably an equivalent should be possible in those cases though. Maybe this isnt too relevant atm
