### ISSUE TITLE
'Default' variable argument usage counterintuitive due to tilde logic

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.core#35]
There is a quirk when trying to use the 'default' variable argument to declare a default value for a possible non existing variable value.

This argument only works if the variable is prefixed with a ~ (tilde). If this is not done, the tag will be printed as is.

Possibly we will need to have a second look at the tilde behavior. With the current behavior the tilde character has to be used quite often and clutters the code a bit IMHO.

**Comment by ttveldhuis** [comment]
The behaviour of the default argument needs a second look I think.

I don’t know if there is another more practical solution for the tilde problem without having also having to modify third party scripts/html each time it uses square brackets. 

Do you have a use case where you have to use the tilde a lot? 

I try to avoid tilde functionality and use that as an enforcement to ensure any object I try to render has all the required variables set, even if that means setting variables to null, false or otherwise.

**Comment by ttveldhuis** [comment]
This has been tackled in the last few commits. default="" is now always parsed, even when there is a tilde present, there are almost no cases in which [varX Y] is used in HTML or Javascript, but we need to see how this works out.
