### ISSUE TITLE
Integrate variable arguments and modifiers

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.core#37]
See title, maybe we should treat them the same?

**Comment by ttveldhuis** [comment]
Can you explain what you exactly mean by ‘treat them the same’?

**Comment by mpwaldhorst** [comment]
Currently in the code there is a differentiation between things like 'default' and '~urlEncode' however maybe to simplify we could just also do ~default. This will make it easier to because you dont need to think if you need or dont need to pass the tilde. Or is it not possible to pass a parameter to those modifiers?

**Comment by ttveldhuis** [comment]
I think you have hit a point here. Variables do actually not really have 'arguments' since there is no function call being made. Addon functions can have direct output so they can have either arguments or modifiers, but variables should only be able to have 'modifiers' I think. Which would mean that `default="x"` should become `*default="x"`.

Do you agree on this?

**Comment by mpwaldhorst** [comment]
Yes that makes sense to me, so functions can have modifiers as well?

**Comment by ttveldhuis** [comment]
The idea is to use the same mechanisme for both, so that instead of;

> [varA x="12" *jsondecode]


Developers can just use;

> [varA x="12" jsondecode]

**Comment by ttveldhuis** [comment]
This has been done per 04c9f97
