### ISSUE TITLE
Static files routed through xentriq should be served with cache headers

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.core#67]
In some cases static files such as CSS, JS or images will need to be routed through Xentriq.
It should be possible to add cache headers for these files.

**Comment by ttveldhuis** [comment]
Planning to introduce `ETag`, `If-Modified-Since`/`Last-Modified` header and `304 Not Modified` status for v1.

In addition to this we can introduce the `Cache-Control: max-age=x` header but we might need to put more though in to that because it allows distinction between public and private as well.

Any other mechanisms we need to consider?

**Comment by mpwaldhorst** [comment]
I think that looks ok for now and should cover most use cases. If we need other things we can implement out of need :)

**Comment by ttveldhuis** [comment]
Implemented in 6d75512
