### ISSUE TITLE
Variable modifiers join & transform-

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.core#69]
Looking at the possible modifiers for variables the following two seem a bit specific:
- transform-
- join

The first looks to be a very specific/strange use-case can you elaborate on its use @ttveldhuis ?

The second is a way to join array values with a comma. 
It is not only a join but also provides a way to provide a selector of a sub-object with the join-field argument (correct me if I'm wrong here).
Maybe this should be simplified so you can join an array of strings string with a delimiter/glue. If sub selection is needed probably asking the user to write a specific function would be a better option.

What are your ideas on this @ttveldhuis ?

**Comment by ttveldhuis** [comment]
**Join**
There are two ways in which the `join` argument can be used, with or without the `join-field` argument;

```
// array is ["A", "B", "C", "D", "E"]
[array join=","] and [array join="-"]

// array is [{ "id": 1, value: "A" }, { "id": 2, value: "B" }, { "id": 3, value: "C" }]
[array join="," join-field="id"] and [array join="-" join-field="value"]
```
renders to 
```
A,B,C,D,E and A-B-C-D-E

1,2,3 and A-B-C
```
This can probably be improved, have any suggestions?

**Transform-**
This is a bit of an obscure argument created out of need in an earlier concept-version of Xentriq, which can now probably replaced by using the language functionalities.

```
// enum is STATUS_NONE
[enum] and [enum transform-STATUS_NONE="There is no status."]
```
renders to 
```
STATUS_NONE and There is no status.
```
Basically when the value to be rendered matches the value after `transform-` it renders the arguments value instead. Because the language functionality supports tags I think it might be best to remove the transform- functionality.

**Comment by mpwaldhorst** [comment]
I think the transform- is indeed a bit obscure. I would suggest removing this.

Regarding the join I'm inclined to suggest removing the join-field option. 
Using `join` with `join-field` basically gives the user a very limited `array_map` functionality.
This looks to me like something that if you want to do should be done in an addon method as it probably means the data needs to be prepared a bit more before it goes to the template.

**Comment by mpwaldhorst** [comment]
Adressed by latest changes
